---
# A YAML file is used over other popular settings file formats due to the ability to use comments and nested structures.
#
# See 
# https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started
# for YAML documentation.
fps : 30
filename_vid : "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any-Alemussy-ryllus-and-kalidon-360p.mp4"
image_scan_type :

# The parameter crop_scale determines how large the cropped image in the centre should be.
# If it's too small, there is a chance that images with some black in the middle
# will be falsely counted as a black screen. If it is too large, there is a chance
# that the cropped image also includes pixels outside of the game video (e.g.
# twitch layout), which would most likely not be black.
crop_scale :
  width : 3
  height : 3