---
# A YAML file is used over other popular settings file formats due to the ability to use comments and nested structures.
#
# See 
# https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started
# for YAML documentation.

# These are the two options. MAKE SURE the image_scan_type matches the string exactly.
CONST_IMAGE_SCAN_TYPE_VIDEO: "video"
CONST_IMAGE_SCAN_TYPE_SCREEN: "screen"

# Determines whether to scan a video or scan the screen.
#image_scan_type: "screen"
image_scan_type: "video"

vid:
  # fps of the video file, not the game.
  fps: 30
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus-no-sp/voll-360p.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus/dudek-360p.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any/Touh.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any/Alemussy/Alemussy-144p.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any/Alemussy/Alemussy-360p.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus-no-sp/emeralve-360p.mp4"

  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus-no-sp/emeralve-720p.mp4"

#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus-no-sp/alemussy-360p.mp4"

screen:
  res_default: [1920, 1080]

# Here is a list of the loads in order, so that you know which number corresponds to which load:
# 1.) Pokitaru
# 2.) Ryllus
# 3.) Kalidon
# 4.) Metallis (ratchet floating)
# 5.) Giant Clank 1
# 6.) Dreamtime
# 7.) Medical Outpost Omega
# 8.) Remains
# 9.) Challax 1 (before giant clank 2)
# 10.) Giant Clank 2 (only in wrench only and 100%)
# 11.) Challax 2 (after giant clank 2, only in wrench only and 100%)
# 12.) Dayni Moon 1
# 13.) IC ratchet (using the shrink ray)
# 14.) Dayni Moon 2 (ratchet floating)
# 15.) Quodrona

# Set to true if the poki load is sped up in the video. This is common
# as speed runners use the speed hack on emulator to skip the first load fast.
poki_sped_up: True

# TODO try run the program with no loads skipped at all.
# Specify loads to skip, as they cause issues in the program, and don't have much load time variation anyway.
loads_to_skip: [
  4, # Metallis
  5  # Giant Clank 1
]

# Load bounds in seconds, in the format [min load time, max load time].
#
# Stops other image frames between black screens throughout the run
# from accidentally being counted as a load.
# Example - ship proxies produce black screens, and the gameplay can
# be counted as a load if these bounds are not applied.
# TODO update poki bounds with real values, if needed.
load_bounds:
  [
  # Pokitaru (fake values because we don't actually include the Pokitaru load time in the speed run,
  # and fake values work good enough for the program.
  [5, 20],
  [12.783, 17.202], # Ryllus
  [12.809, 17.189], # Kalidon
  [4.705, 4.772], # Metallis
  [2.457, 2.491], # Giant Clank 1
  [17.046, 17.299], # Dreamtime
  [12.764, 15.515], # Medical Outpost Omega
  [12.707, 17.117], # Remains
  [12.798, 17.192], # Challax 1
#  [2.413, 2.437], # Giant Clank 2 (for wrench only and 100%)
#  [14.987, 15.015], # Challax 2 (after giant clank 2, only in wrench only and 100%)
  [12.683, 17.132], # Dayni Moon 1
  [2.401, 2.546], # IC ratchet (using the shrink ray)
  [2.624, 2.703], # Dayni Moon 2 (ratchet floating)
  [13.376, 15.622], # Quodrona
  ]

# Black screen bounds in seconds, in the format
#  [[MIN black screen 1, MAX black screen 1],
#  [MIN black screen 2, MAX black screen 2]]
#
# Stops other image frames between black screens throughout the run
# from accidentally being counted as a load.
# Example - ship proxies produce black screens, and the gameplay can
# be counted as a load if the length of the black screen is not measured.
#
# IGNORE means that no bounds are taken into account. We only want to check
# bounds when needed, so that we do not stop other valid loads from being
# counted by accident.
black_screen_bounds:
  [
  IGNORE, # Pokitaru
  IGNORE, # Ryllus
  IGNORE, # Kalidon
  IGNORE, # Metallis
  IGNORE, # Giant Clank 1
  IGNORE, # Dreamtime
  IGNORE, # Medical Outpost Omega
  IGNORE, # Remains
  [[0.333333, 0.666666], IGNORE], # Challax 1 - first black screen is between 10 and 20 frames.
#  IGNORE, # Giant Clank 2 (for wrench only and 100%)
#  IGNORE, # Challax 2 (after giant clank 2, only in wrench only and 100%)
  IGNORE, # Dayni Moon 1
  IGNORE, # IC ratchet (using the shrink ray)
  IGNORE, # Dayni Moon 2 (ratchet floating)
  IGNORE, # Quodrona
  ]

# The parameter crop_scale determines how large the cropped image in the centre should be.
# If it's too small, there is a chance that images with some black in the middle
# will be falsely counted as a black screen. If it is too large, there is a chance
# that the cropped image also includes pixels outside of the game video (e.g.
# twitch layout), which would most likely not be black.
#crop_scale:
#  width: 1
#  height: 1

# Some supported video resolutions are taken from https://typito.com/blog/best-video-format-for-youtube/.
# All of them are currently 16:9 (widescreen) resolutions, which is the most common.
# Be cautious when adding more video resolutions, as the tuning of the crop size might
# not be as fine when the greatest common denominator of video resolutions turns out to be a small number.
#res_supported: [[256, 144],
#                [640, 360],
#                [1280, 720],
#                [1920, 1080],
#                [2560, 1440],
#                [3840, 2160]]