---
# A YAML file is used over other popular settings file formats due to the ability to use comments and nested structures.
#
# See 
# https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started
# for YAML documentation.

# These are the two options. MAKE SURE the image_scan_type matches the string exactly.
CONST_IMAGE_SCAN_TYPE_VIDEO: "video"
CONST_IMAGE_SCAN_TYPE_SCREEN: "screen"

# Determines whether to scan a video or scan the screen.
#image_scan_type: "screen"
image_scan_type: "video"

vid:
  fps: 30
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus-no-sp/voll-360p.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/ng-plus/dudek-360p.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any/Touh.mp4"
#  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any/Alemussy/Alemussy-144p.mp4"
  filename_vid: "C:/Users/josho/Desktop/Big-Brother/vids/autosplitting/any/Alemussy/Alemussy-360p.mp4"

# Set to true if the poki load is sped up in the video. This is common
# as speed runners use the speed hack on emulator to skip the first load fast.
poki_sped_up: False

screen:
  res_default: [1920, 1080]

# Load bounds in seconds, in the format [min load time, max load time].
#
# Stops other image frames between black screens throughout the run
# from accidentally being counted as a load.
# Example - ship proxies produce black screens, and the gameplay can
# be counted as a load if these bounds are not applied.
# TODO update poki bounds with real values.
load_bounds:
  [[5, 20], # Pokitaru
  [12.783, 17.202], # Ryllus
  [12.809, 17.189]] # Kalidon

# The parameter crop_scale determines how large the cropped image in the centre should be.
# If it's too small, there is a chance that images with some black in the middle
# will be falsely counted as a black screen. If it is too large, there is a chance
# that the cropped image also includes pixels outside of the game video (e.g.
# twitch layout), which would most likely not be black.
crop_scale:
  width: 1
  height: 1

# Some supported video resolutions are taken from https://typito.com/blog/best-video-format-for-youtube/.
# All of them are currently 16:9 (widescreen) resolutions, which is the most common.
# Be cautious when adding more video resolutions, as the tuning of the crop size might
# not be as fine when the greatest common denominator of video resolutions turns out to be a small number.
res_supported: [[256, 144],
                [640, 360],
                [1280, 720],
                [1920, 1080],
                [2560, 1440],
                [3840, 2160]]